# Fit a state-space model to predict performance

To evaluate skill across time, we need to take into account trial-type difficulty.

Use a state-space model to fit to performance as a function of trial type.

Can use:

- scipy.signal.StateSpace <https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.StateSpace.html> or
- pykalman.KalmanFilter <https://pykalman.github.io/> or
- control.StateSpace <https://python-control.readthedocs.io/en/latest/generated/control.StateSpace.html>

Slides for reference <https://www.halvorsen.blog/documents/programming/python/resources/powerpoints/State%20Space%20Models%20with%20Python.pdf>


## Set up


In [1]:
# Set up to use local modules
%load_ext autoreload
%autoreload 2
import os
import sys
module_path = os.path.abspath(os.path.join('..'))
sys.path.insert(0, module_path)

In [2]:
# Fit a state-space model to performance data, taking into account the trial type
# and the difficulty of the trial

"""
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm

from state_space import StateSpace
"""

# See a possible example here
# https://www.statsmodels.org/dev/examples/notebooks/generated/statespace_fixed_params.html

import scipy
import numpy as np

In [3]:
## State-space model

In [4]:
# Example from the documentation
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.StateSpace.html

a = np.array([[0, 1], [0, 0]])
b = np.array([[0], [1]])
c = np.array([[1, 0]])
d = np.array([[0]])
sys = scipy.signal.StateSpace(a, b, c, d)
print(sys)

StateSpaceContinuous(
array([[0, 1],
       [0, 0]]),
array([[0],
       [1]]),
array([[1, 0]]),
array([[0]]),
dt: None
)


In [5]:
sys.to_discrete(0.1)

StateSpaceDiscrete(
array([[1. , 0.1],
       [0. , 1. ]]),
array([[0.005],
       [0.1  ]]),
array([[1, 0]]),
array([[0]]),
dt: 0.1
)